[drive_settings]
Weekly_Agenda_ID = "1jcazpKFV5wNjzDY-3oC9BKei_3iVQhrQ6xy3P76G-5w"
Source_Music_Folder = "12y2cjGE7GE3MTJ8QtNs3_Z5L30o5Ql6D" # The LTBB folder containing all the sheet music. Currently organized in folders like 'A-C', 'D-F', etc
Destination_Music_Folder = "1h-T2mnFrr0VpafBDJ3nv3vvO_xLGir9t" # The folder where the MobileSheets database and PDFs will end up
Seasonal_Songs = "1M7sLr9wwvHJIfKGijRTSjC5ae1CODzbY" # Some subfolders that contain additional songs not in the alphabetic folders
Drive_ID = "0AIscw8ywGnshUk9PVA" # Quirk of using a Shared Drive, we sometimes need this value
Ignore_Folders = ['1. Member Drafts', '2. Seasonal Songs', '3. Warm-ups', '4. 3rd Rail Drumline', '5. Resources', '6. Recordings']

[instrumentation.instruments]
# Names by which these instruments might appear in the titles of the PDF files - includes some interesting typos
Score = ["Score"]
Tuba = ["Tuba", "Sousaphone", "Sousa", "Low Brass", "Basses", "Bass (Treble Clef)", "Bass_Line"]
Horn = ["Horn in F", "F Horn", "Mellophone", "Horns F"]
Percussion = ["Percussion", "Drum", "Snareline", "Perc", "BassDr", "Snare", "Congo", "Toms", "Quads", "Cymbal", "Glockenspiel"]
Clarinet = ["Clarinet", "Bb Sopranos"]
"Soprano Sax" = ["Soprano"]
"Alto Sax" = ["Alto"]
"Tenor Sax" = ["Tenor"]
"Bari Sax" = ["Bari"]
"Bass Sax" = ["Bass Sax", "Bass Saxophone"]
Trumpet = ["Trumpet", "Flugelhorn", "Trmp", "Trumplet"]
Trombone = ["Trombone", "Tbn", "Trmb", "Bone", "Low Brass"]
"Eb Horn" = ["Eb Horn", "Horn in Eb"]
Flute = ["Flute", "C Woodwind"]
Euph = ["Euphonium", "Euph", "B Flat Bass (Trebel Cleff)"]

# Does your instrument not have a part for this song? Use a backup part!
# Horn included as a backup here so we don"t accidentally pick up a zillion Eb Horns without at least trying things like "Horn in F" first
[instrumentation.backup_instruments]
Score = []
Tuba = ["Bass Clef Instruments"]
Horn = ["F Treble Clef Instruments", "Horn"]
Percussion = []
Clarinet = ["Bb Treble Clef Instruments"]
"Soprano Sax" = ["Bb Treble Clef Instruments", "Tenor Sax"]
"Alto Sax" = ["Eb Treble Clef Instruments"]
"Tenor Sax" = ["Bb Treble Clef Instruments"]
"Bari Sax" = ["Eb Treble Clef Instruments"]
"Bass Sax" = ["Bb Treble Clef Instruments", "Tuba"]
Trumpet = ["Bb Treble Clef Instruments"]
Trombone = ["Bass Clef Instruments"]
"Eb Horn" = ["Eb Treble Clef Instruments", "Bari Sax"]
Flute = ["C Treble Clef Instruments"]
Euph = ["Eb Treble Clef Instruments", "Tenor Sax"]

# Separate Soloist parts
[instrumentation.solo_parts]
Score = []
Tuba = ["Soloist (Bass Clef)"]
Horn = ["Soloist (F)"]
Percussion = []
Clarinet = ["Soloist (Bb)"]
"Soprano Sax" = ["Soloist (Bb)"]
"Alto Sax" = ["Soloist (Eb)"]
"Tenor Sax" = ["Soloist (Bb)"]
"Bari Sax" = ["Soloist (Eb)"]
"Bass Sax" = ["Soloist (Bb)"]
Trumpet = ["Soloist (Bb)"]
Trombone = ["Soloist (Bass Clef)"]
"Eb Horn" = ["Soloist (Eb)"]
Flute = ["Soloist (C)"]
Euph = ["Soloist (Bb)"]

# These are specific files that have names that don't indicate what part they are
[exceptions]
Score = [
    "Sleigh Bells - Christmas Wrapping_v3.1.pdf",
    "F It Up - CHORDS.pdf",
    "Karma Chameleon v1.1.pdf",
    "Sleigh Bells - Last Christmas_v2.pdf",
    "Liar V2.pdf",
    "Running Up That Hill v1.2.pdf",
    "Spookier_Guy_v1.3.pdf",
    "Way_Less_Sad_1.4.pdf",
    "Where's Evan.pdf",
    "Wipe_Eauxt_1_2.pdf"
]